exports.twitterKeys = {

  TWITTER_CONSUMER_KEY =	"V6RMtsCVNgrHhE5qrfkkeeVtS",
  TWITTER_CONSUMER_SECRET =	"pGIOK0IYRnTsX6iD2z2TV1fR7Rv4CCgmJcdlj1jlzIO264MEzt",
  TWITTER_ACCESS_TOKEN_KEY =	"59610776-HhUkm2XhJBRCUzmJvmR6C5qmw5oUf7UNeLByunYiV",
  TWITTER_ACCESS_TOKEN_SECRET = "NtFOpXEtGI60LZo8gtZCQTIFOw0cdeWTavsu8BPHWtPWP"
}